version: 2.1

jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Building Program (EZHTML.cpp) and creating an executable (EZHTML)
          command: 'g++ EZHTML.cpp -o EZHTML'
      - run:
          name: Executing EZHTML
          command: './EZHTML'